# Домашнее задание HW01
## Работа с библиотекой NumPy

In [1]:
# 1. Импорт библиотеки NumPy с общепринятым сокращением
import numpy as np

In [2]:
# 2. Примеры создания массивов

# Создание массива из обычного списка Python
list_data = [1, 2, 3, 4, 5]
array_from_list = np.array(list_data)
print("Массив из списка:", array_from_list)

# Создание двумерного массива из вложенного списка
matrix_data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix_from_list = np.array(matrix_data)
print("Двумерный массив:")
print(matrix_from_list)

# Создание массива из нулей
zeros_array = np.zeros(5)
print("Массив из нулей:", zeros_array)

# Создание двумерного массива из единиц
ones_matrix = np.ones((3, 3))
print("Массив 3x3 из единиц:")
print(ones_matrix)

# Создание массива с помощью arange (аналог range)
range_array = np.arange(0, 10, 2)  # от 0 до 10 с шагом 2
print("Массив с помощью arange:", range_array)

# Создание массива равномерно распределенных значений
linspace_array = np.linspace(0, 1, 5)  # 5 значений от 0 до 1
print("Массив с помощью linspace:", linspace_array)

Массив из списка: [1 2 3 4 5]
Двумерный массив:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Массив из нулей: [0. 0. 0. 0. 0.]
Массив 3x3 из единиц:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Массив с помощью arange: [0 2 4 6 8]
Массив с помощью linspace: [0.   0.25 0.5  0.75 1.  ]


In [3]:
# 3. Демонстрация атрибутов массивов

print("Исходный двумерный массив:")
print(matrix_from_list)
print("Форма (shape) массива:", matrix_from_list.shape)  # Размерность массива
print("Тип данных (dtype) массива:", matrix_from_list.dtype)  # Тип элементов
print("Размерность (ndim):", matrix_from_list.ndim)  # Количество измерений
print("Общее количество элементов:", matrix_from_list.size)  # Всего элементов

Исходный двумерный массив:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Форма (shape) массива: (3, 3)
Тип данных (dtype) массива: int64
Размерность (ndim): 2
Общее количество элементов: 9


In [4]:
# 4. Примеры индексирования и срезов

# Создаем демонстрационный массив
demo_array = np.array([[1, 2, 3, 4], 
                       [5, 6, 7, 8], 
                       [9, 10, 11, 12]])

print("Исходный массив:")
print(demo_array)

# Получение отдельного элемента
print("\nОтдельный элемент [1, 2]:", demo_array[1, 2])  # Строка 1, столбец 2

# Извлечение подмассива с помощью среза
# Первые две строки, столбцы с 1 по 3
sub_array = demo_array[:2, 1:3]
print("Срез [:2, 1:3]:")
print(sub_array)

# Все строки, каждый второй столбец
column_slice = demo_array[:, ::2]
print("Срез [:, ::2] (каждый второй столбец):")
print(column_slice)


Исходный массив:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Отдельный элемент [1, 2]: 7
Срез [:2, 1:3]:
[[2 3]
 [6 7]]
Срез [:, ::2] (каждый второй столбец):
[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [5]:
# 5. Примеры векторных операций и базовых статистик

# Создаем два массива для операций
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print("Массив a:", a)
print("Массив b:", b)

# Поэлементное сложение
sum_arrays = a + b
print("Поэлементная сумма a + b:", sum_arrays)

# Поэлементное умножение
mult_arrays = a * b
print("Поэлементное умножение a * b:", mult_arrays)

# Математические операции с скалярами
power_array = a ** 2
print("Квадраты элементов массива a:", power_array)

# Базовые статистические функции
print("\nСтатистики для массива a:")
print("Среднее значение:", np.mean(a))
print("Стандартное отклонение:", np.std(a))
print("Сумма элементов:", np.sum(a))
print("Минимальное значение:", np.min(a))
print("Максимальное значение:", np.max(a))

# Статистики по осям для двумерного массива
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

print("\nДвумерный массив:")
print(matrix)
print("Среднее по столбцам (axis=0):", np.mean(matrix, axis=0))
print("Среднее по строкам (axis=1):", np.mean(matrix, axis=1))

Массив a: [1 2 3 4]
Массив b: [5 6 7 8]
Поэлементная сумма a + b: [ 6  8 10 12]
Поэлементное умножение a * b: [ 5 12 21 32]
Квадраты элементов массива a: [ 1  4  9 16]

Статистики для массива a:
Среднее значение: 2.5
Стандартное отклонение: 1.118033988749895
Сумма элементов: 10
Минимальное значение: 1
Максимальное значение: 4

Двумерный массив:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Среднее по столбцам (axis=0): [4. 5. 6.]
Среднее по строкам (axis=1): [2. 5. 8.]
